### ISSUE TITLE
Improve backup section

### ISSUE THREAD

**Issue by NoahMaizels** [ethersphere/bee-docs#343]
* How to backup over ssh
* How to restore backup
* Where to keep backups

**Comment by attila-lendvai** [comment]
some additional questions that i have after reading the backup section:

**what** needs to be backed up so that the node's identity (including staking) can be restored, and everything else is synced back from the network?

my understanding is:
* the eth key from Clef
* the `statestore` directory (but then the doc says that if a node is started after the backup of the `statestore`, then it may get out of sync, or something alike)

is it necessary to stop the node to back up the `statestore` dir?

my ultimate goal is to add a [Guix Shepherd action](https://github.com/attila-lendvai/guix-crypto) that backs up the identity (as opposed to the entire chunk db) of a bee node.

**Comment by attila-lendvai** [comment]
> * How to backup over ssh
> * Where to keep backups

these are generic unix sysadmin questions. as such, IMO, they shouldn't be addressed in the bee docs itself, beyond maybe pointing to external tutorials.
