### ISSUE TITLE
Search aggregator anomaly

### ISSUE THREAD

**Issue by tamas6** [ethersphere/bee-docs#470]
For instance, 
try searching  "Stake" 
try searching  "Storage incentives"

you don't get results from the other, despite they are connected
case study: One tries to participate in the redistribution, visit docs, and search for storage incentives, it completely misses the guide to make it happen ("Staking").

**Comment by NoahMaizels** [comment]
This is because the search plugin is relatively basic, I'm using https://www.npmjs.com/package/docusaurus-lunr-search

I just applied for https://docsearch.algolia.com/ , they have a much more advanced search functionality, I think if they accept my application then I can add it and it should fix this issue. Will update when I hear back.

**Comment by NoahMaizels** [comment]
Could be improved with the addition of Algolia, already addressed in this issue: https://github.com/ethersphere/bee-docs/issues/271
